package model;

public enum PlantType {
    PEASHOOTER,SNOW_PEA,CABBAGE_PULT,REPEATER,THREEPEATER,
    CACTUS,GATLING_PEA,SCAREDY_SHROOM,KARNEL_PULT,
    SPLIT_PEA,EXPLODE_O_NUT,MELON_PULT,LILYPAD,WINTERMELON,WALL_NUT,
    TANGLE_KELP,TALL_NUT,CATTAIL,POTATO_MINE,
    CHERRY_BOMB,SUNFLOWER,TWINSUNFLOWER,JALAPENO

}
